name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (+ dev tools)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pip-audit

      - name: Compile sources (fast syntax check)
        run: python -m py_compile *.py || true

      - name: Wait for Mongo to be reachable
        run: |
          python - <<'PY'
          import time, sys
          from pymongo import MongoClient
          for _ in range(60):
              try:
                  MongoClient("mongodb://localhost:27017", serverSelectionTimeoutMS=1000).admin.command("ping")
                  print("Mongo is up"); sys.exit(0)
              except Exception:
                  time.sleep(1)
          print("Mongo did not come up", file=sys.stderr); sys.exit(1)
          PY

      - name: Smoke test with Flask test client
        env:
          API_KEY: "ci-key"
          ALLOW_CLEAR: "true"
          MONGO_URI: "mongodb://localhost:27017"
          MONGO_DB: "cleancommute_ci"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import os, json
          os.environ.setdefault("API_KEY", "ci-key")
          os.environ.setdefault("ALLOW_CLEAR", "true")
          os.environ.setdefault("MONGO_URI", "mongodb://localhost:27017")
          os.environ.setdefault("MONGO_DB", "cleancommute_ci")

          try:
              from app import app
          except Exception as e:
              raise AssertionError(f"Import failed (expected 'from app import app'): {e}")

          c = app.test_client()

          def J(r):
              try: return json.loads(r.data.decode("utf-8"))
              except Exception: raise AssertionError(f"Non-JSON: {r.status_code} {r.data[:200]!r}")

          def as_list(p):
              if isinstance(p, list): return p
              if isinstance(p, dict) and isinstance(p.get("data"), list): return p["data"]
              raise AssertionError(f"Expected list or {{'data': list}}, got: {p!r}")

          r = c.get("/api/v1/health"); b=J(r); assert r.status_code==200 and b.get("ok") in (True,1)
          r = c.get("/api/v1/db-ping"); _=J(r); assert r.status_code in (200,500)

          r = c.get("/api/v1/samples"); samples=as_list(J(r)); assert r.status_code==200 and isinstance(samples, list)

          r = c.post("/api/v1/samples", json={"name":"CI"})
          assert r.status_code==401 and r.headers.get("WWW-Authenticate","").startswith("API-Key")

          r = c.post("/api/v1/samples", json={"name":"CI"}, headers={"x-api-key": os.environ["API_KEY"]})
          b=J(r); assert r.status_code==201; _id=b["data"]["_id"] if "data" in b else b["_id"]; assert isinstance(_id,str) and _id

          r = c.post("/api/v1/commutes",
                     json={"origin":"A","destination":"B","mode":"driving"},
                     headers={"x-api-key": os.environ["API_KEY"]})
          b=J(r); assert r.status_code==201; _id=b["data"]["_id"] if "data" in b else b["_id"]; assert isinstance(_id,str)

          r = c.get("/api/v1/commutes"); items=as_list(J(r)); assert r.status_code==200 and isinstance(items, list)

          r = c.post("/api/v1/commutes/clear", headers={"x-api-key": os.environ["API_KEY"]}); assert r.status_code==200
          r = c.post("/api/v1/samples/clear", headers={"x-api-key": os.environ["API_KEY"]}); assert r.status_code==200
          print("✅ Smoke OK")
          PY

      # Style: Ruff strict, Black autoformat (never fails build)
      - name: Style (ruff + black autoformat)
        run: |
          ruff check .
          black .
          echo "✅ Style checks passed (Black autoformatted if needed)."

      - name: Vulnerability scan (pip-audit; non-blocking)
        run: pip-audit -r requirements.txt || true

  deploy_staging:
    name: Deploy to Heroku (staging)
    runs-on: ubuntu-latest
    needs: smoke
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Heroku CLI
        uses: heroku/actions/setup@v2

      - name: Deploy via git to Heroku (staging)
        uses: heroku/actions/deploy-via-git@v2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP_STAGING }}
          branch: staging

      - name: (Optional) Set config vars (staging) if provided
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ vars.HEROKU_APP_STAGING }}
          API_KEY: ${{ secrets.API_KEY_STAGING }}
          MONGO_URI: ${{ secrets.MONGO_URI_STAGING }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN_STAGING }}
          DEFAULT_LIMITS: ${{ secrets.DEFAULT_LIMITS }}
          LIMITER_STORAGE_URI: ${{ secrets.LIMITER_STORAGE_URI }}
        run: |
          set_kv=""
          [ -n "$API_KEY" ] && set_kv="$set_kv API_KEY=$API_KEY"
          [ -n "$MONGO_URI" ] && set_kv="$set_kv MONGO_URI=$MONGO_URI"
          [ -n "$FRONTEND_ORIGIN" ] && set_kv="$set_kv FRONTEND_ORIGIN=$FRONTEND_ORIGIN"
          [ -n "$DEFAULT_LIMITS" ] && set_kv="$set_kv DEFAULT_LIMITS=$DEFAULT_LIMITS"
          [ -n "$LIMITER_STORAGE_URI" ] && set_kv="$set_kv LIMITER_STORAGE_URI=$LIMITER_STORAGE_URI"
          if [ -n "$set_kv" ]; then
            heroku config:set $set_kv -a "$HEROKU_APP"
          else
            echo "No config vars provided; skipping"
          fi

      - name: Health check (staging)
        run: |
          set -e
          URL="https://${{ vars.HEROKU_APP_STAGING }}.herokuapp.com/api/v1/health"
          echo "Checking $URL"
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL") || true
            if [ "$code" = "200" ]; then echo "Healthy ✅"; exit 0; fi
            sleep 2
          done
          echo "Health check failed ❌"; exit 1

  deploy_prod:
    name: Deploy to Heroku (production)
    runs-on: ubuntu-latest
    needs: smoke
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Heroku CLI
        uses: heroku/actions/setup@v2

      - name: Deploy via git to Heroku (prod)
        uses: heroku/actions/deploy-via-git@v2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP_PROD }}
          branch: main

      - name: (Optional) Set config vars (prod) if provided
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ vars.HEROKU_APP_PROD }}
          API_KEY: ${{ secrets.API_KEY_PROD }}
          MONGO_URI: ${{ secrets.MONGO_URI_PROD }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN_PROD }}
          DEFAULT_LIMITS: ${{ secrets.DEFAULT_LIMITS }}
          LIMITER_STORAGE_URI: ${{ secrets.LIMITER_STORAGE_URI }}
        run: |
          set_kv=""
          [ -n "$API_KEY" ] && set_kv="$set_kv API_KEY=$API_KEY"
          [ -n "$MONGO_URI" ] && set_kv="$set_kv MONGO_URI=$MONGO_URI"
          [ -n "$FRONTEND_ORIGIN" ] && set_kv="$set_kv FRONTEND_ORIGIN=$FRONTEND_ORIGIN"
          [ -n "$DEFAULT_LIMITS" ] && set_kv="$set_kv DEFAULT_LIMITS=$DEFAULT_LIMITS"
          [ -n "$LIMITER_STORAGE_URI" ] && set_kv="$set_kv LIMITER_STORAGE_URI=$LIMITER_STORAGE_URI"
          if [ -n "$set_kv" ]; then
            heroku config:set $set_kv -a "$HEROKU_APP"
          else
            echo "No config vars provided; skipping"
          fi

      - name: Health check (prod)
        run: |
          set -e
          URL="https://${{ vars.HEROKU_APP_PROD }}.herokuapp.com/api/v1/health"
          echo "Checking $URL"
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$URL") || true
            if [ "$code" = "200" ]; then echo "Healthy ✅"; exit 0; fi
            sleep 2
          done
          echo "Health check failed ❌"; exit 1
