name: Deploy to Heroku
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure Heroku CLI exists (prevents "heroku: not found")
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Show Heroku version
        run: heroku --version

      # Authenticate with API key (no username/password)
      - name: Auth Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login _
            password $HEROKU_API_KEY
          machine git.heroku.com
            login _
            password $HEROKU_API_KEY
          EOF

      # Push to your existing app (no auto-create)
      - name: Push to Heroku
        run: |
          heroku git:remote -a cleancommute-api-python
          git push heroku HEAD:main -f
