name: deploy-heroku
on:
  push:
    branches: ["main"]
    paths:
      - "**.py"
      - "requirements.txt"
      - "Procfile"
      - ".github/workflows/deploy-heroku.yml"
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches the full git history
      
      # Push the current commit to Heroku via Git (no third-party action)
      - name: Deploy via Git to Heroku
        env:
          HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
          git push heroku HEAD:main -f
