name: Deploy to Heroku
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # full history (not shallow)

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Show Heroku version
        run: heroku --version

      - name: Auth Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login _
            password $HEROKU_API_KEY
          machine git.heroku.com
            login _
            password $HEROKU_API_KEY
          EOF

      - name: Ensure not shallow (belt & suspenders)
        run: |
          if git rev-parse --is-shallow-repository | grep -q true; then
            git fetch --unshallow --tags
          else
            git fetch --tags
          fi

      - name: Push to Heroku
        env:
          APP_NAME: clean-commute-api-python   # <-- fixed (with dash)
        run: |
          git remote remove heroku 2>/dev/null || true
          heroku git:remote -a "$APP_NAME"
          git push heroku HEAD:main
