name: deploy-heroku
on:
  push:
    branches: ["main"]
    paths:
      - "**.py"
      - "requirements.txt"
      - "Procfile"
      - ".github/workflows/deploy-heroku.yml"
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Build check
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.2.1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email:     ${{ secrets.HEROKU_EMAIL }}
